### ISSUE TITLE
Assign score to host results

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/naabu#294]
### Please describe your feature request:
The JSON result should be assigned a numeric score ranging from 0 to 100. A higher value would mean that the results are realistic. Instead, a value near zero means that the results are likely false positive. The calculation of such a number should be influenced by various factors, for example:
- [ ] if multiple retries yielded the same open ports results
- [x] If the open ports were detected previously (#293)
- [x] If the same host exposes a lot of open ports (#379)
- [ ] If the service detection (actually not implemented) will confirm the port to be open

### Describe the use case of this feature:
Potentially this could be helpful to filter out noise from results (ref. https://github.com/projectdiscovery/naabu/pull/292#issuecomment-1095762286)

**Comment by Mzack9999** [comment]
Probably redundant with nuclei network protocol - Closing as of now, will be reopened in the future if necessary
